### ISSUE TITLE
Unable to tunnel through proxy when connecting to Clickhouse after upgrade

### ISSUE THREAD

**Issue by djuarezg** [ClickHouse/metabase-clickhouse-driver#118]
We were using 0.8.1 version with Metabase 0.45.1 as when upgrading to 0.9.X for this driver we get the following:

```
Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden", server ClickHouseNode [uri=https://<haproxy_nodename>:9001/default, options={sslrootcert=/etc/certs/cert_ca.crt,use_server_time_zone_for_dates=true}]@1759509224
```

Until now this was never reported as an error, and I did not see anything in the changes that could explain this not working anymore.

**Comment by slvrtrn** [comment]
Can you please provide more details about your CH setup? For example, what is the network configuration in this scenario? I see that you have HAProxy and some certificates in there.

**Comment by djuarezg** [comment]
We are running:

* Clickhouse `"22.8.8.3"`, in a cluster mode, with a HAProxy in front of it
* Metabase `0.45.1`
* Trying to use this driver on `0.9.0` or `0.9.1`
IP table rules have not changed between versions, neither has HAproxy conf, so basically the driver version is the limiting factor here, I can reproduce it by switching back and forth with the driver jar file

I saw that there are now options for https://www.metabase.com/docs/v0.45/databases/ssh-tunnel and `Additional JDBC connection string options`

**Comment by djuarezg** [comment]
I suspect this may be happening due to the `JDBC` update

**Comment by djuarezg** [comment]
I found https://www.oracle.com/java/technologies/javase/8u111-relnotes.html, but running Metabase as a container with the following `env` does not make any difference:

```
JAVA_HOME=/opt/java/openjdk
JAVA_OPTS=-Xmx1g -Dhttp.proxyHost=proxy.plabs.ch -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.plabs.ch -Dhttps.proxyPort=3128 -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.http.auth.proxying.disabledSchemes=""
```

**Comment by djuarezg** [comment]
Extra info, this is an extract of the underlying exception:

```
Caused by: java.sql.SQLException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden", server ClickHouseNode [uri=https://vmk-tdtproxy-01.data.plabs.ch:9001/raw, options={socket_timeout=3600000,sslrootcert=/etc/certs/cert_ca.crt,use_server_time_zone_for_dates=true}]@-411175026
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:93)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:298)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:241)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at metabase.plugins.jdbc_proxy$proxy_driver$reify__62973.connect(jdbc_proxy.clj:33)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at metabase.connection_pool$proxy_data_source$reify__12279.getConnection(connection_pool.clj:29)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 403 Forbidden"
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:237)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)

```

**Comment by djuarezg** [comment]
Could it be related to https://github.com/ClickHouse/clickhouse-jdbc/commit/9be9db2f43539ef5c7a7cad1451ca678c617a63a ?

**Comment by djuarezg** [comment]
It seems that after the JDBC update, we need an extra option for the Additional JDBC connection string options:

`use_no_proxy=true`

**Comment by djuarezg** [comment]
@slvrtrn Correct me if I am wrong but doesn't the variable name do the opposite of what it means?

**Comment by slvrtrn** [comment]
@djuarezg it is indeed a bit awkward. I will add this option in the next release (which is _soon_)

**Comment by slvrtrn** [comment]
@djuarezg I apologize for the delay.

0.9.2 is out. Could you verify that it indeed solves the issue?

![image](https://user-images.githubusercontent.com/3175289/213525251-d4695c5a-fd78-44b3-86b1-d403acf0c517.png)

**Comment by slvrtrn** [comment]
Since there is a fix that likely resolves the issue, I am closing this due to inactivity.

**Comment by djuarezg** [comment]
sorry for the late response, but it works flawlessly!
