### ISSUE TITLE
Table sync failing with exception

### ISSUE THREAD

**Issue by phil-schreiber** [ClickHouse/metabase-clickhouse-driver#123]
Hi there, 

we're happy users of this community effort, thanks to all maintainers and contributers!
But recently we're having an issue.

We're running metabase in version 0.45.1 and clickhouse driver in version 0.9.1

The **table sync** (triggered from metabase UI) process fails with the following exception:

`java.lang.IllegalArgumentException: Unknown aggregate function: minIf`

The minIf should be supported. It works fine when creating the materialized view.

Full log looks like this:

```
2023-01-16 10:18:15 | at java.base/java.lang.Thread.run(Unknown Source) |  
-- | -- | --
  |   | 2023-01-16 10:18:15 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) |  
  |   | 2023-01-16 10:18:15 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) |  
  |   | 2023-01-16 10:18:15 | at java.base/java.util.concurrent.FutureTask.run(Unknown Source) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.AFn.call(AFn.java:18) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047) |  
  |   | 2023-01-16 10:18:15 | at metabase.api.database$fn__78701$fn__78702.invoke(database.clj:890) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata$fn__69987$sync_db_metadata_BANG___69992.invoke(sync_metadata.clj:46) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata$fn__69987$sync_db_metadata_BANG___69992$fn__69993.invoke(sync_metadata.clj:49) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_sync_operation.invoke(util.clj:178) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:181) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_duplicate_ops_prevented$fn__42712.invoke(util.clj:67) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_sync_events$fn__42721.invoke(util.clj:88) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_logging$fn__42726.invoke(util.clj:114) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_db_logging_disabled$fn__42737.invoke(util.clj:129) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$sync_in_context$fn__42740.invoke(util.clj:138) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.MultiFn.invoke(MultiFn.java:239) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver$fn__33693.invoke(driver.clj:626) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver$fn__33693.invokeStatic(driver.clj:626) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$partial$fn__5910.invoke(core.clj:2647) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_with_error_handling.invoke(util.clj:153) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:160) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata$fn__69987$sync_db_metadata_BANG___69992$fn__69993$fn__69994.invoke(sync_metadata.clj:50) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__43040$run_sync_operation__43045.invoke(util.clj:487) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__43040$run_sync_operation__43045$fn__43046.invoke(util.clj:493) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__43040$run_sync_operation__43045$fn__43046$fn__43054.invoke(util.clj:495) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__42819$run_step_with_metadata__42824.invoke(util.clj:378) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__42819$run_step_with_metadata__42824$fn__42828.invoke(util.clj:383) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.RestFn.invoke(RestFn.java:397) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$fn__42819$run_step_with_metadata__42824$fn__42828$fn__42830.doInvoke(util.clj:388) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$apply.invoke(core.clj:662) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$apply.invokeStatic(core.clj:669) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.AFn.applyTo(AFn.java:144) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.AFn.applyToHelper(AFn.java:154) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields$fn__68420$sync_fields_BANG___68425.invoke(fields.clj:77) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields$fn__68420$sync_fields_BANG___68425$fn__68426.invoke(fields.clj:85) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$apply.invoke(core.clj:662) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$apply.invokeStatic(core.clj:669) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.RestFn.applyTo(RestFn.java:130) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.RT.boundedLength(RT.java:1790) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.Cons.next(Cons.java:39) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.LazySeq.seq(LazySeq.java:51) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.LazySeq.sval(LazySeq.java:42) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$filter$fn__5962.invoke(core.clj:2826) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$seq__5467.invokeStatic(core.clj:139) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.RT.seq(RT.java:535) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.LazySeq.seq(LazySeq.java:51) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.LazySeq.sval(LazySeq.java:42) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$map$fn__5935.invoke(core.clj:2770) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$partial$fn__5908.invoke(core.clj:2641) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields$fn__68382$sync_fields_for_table_BANG___68391.invoke(fields.clj:65) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields$fn__68382$sync_fields_for_table_BANG___68391$fn__68394.invoke(fields.clj:71) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_with_error_handling.invoke(util.clj:153) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:160) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields$fn__68382$sync_fields_for_table_BANG___68391$fn__68394$fn__68395.invoke(fields.clj:72) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields.fetch_metadata$fn__67881$db_metadata__67886.invoke(fetch_metadata.clj:85) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.sync_metadata.fields.fetch_metadata$fn__67881$db_metadata__67886$fn__67887.invoke(fetch_metadata.clj:89) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.fetch_metadata$fn__67613$table_metadata__67618.invoke(fetch_metadata.clj:16) |  
  |   | 2023-01-16 10:18:15 | at metabase.sync.fetch_metadata$fn__67613$table_metadata__67618$fn__67619.invoke(fetch_metadata.clj:19) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.MultiFn.invoke(MultiFn.java:239) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.clickhouse$fn__82892.invoke(clickhouse.clj:514) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.clickhouse$fn__82892.invokeStatic(clickhouse.clj:516) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invoke(describe_table.clj:197) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invokeStatic(describe_table.clj:204) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:190) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:193) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.MultiFn.invoke(MultiFn.java:244) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$fn__61521.invoke(describe_table.clj:171) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$fn__61521.invokeStatic(describe_table.clj:173) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$into.invoke(core.clj:6950) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$into.invokeStatic(core.clj:6962) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$transduce.invokeStatic(core.clj:6946) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__61502.reduce(describe_table.clj:140) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$reduce.invoke(core.clj:6868) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$reduce.invokeStatic(core.clj:6885) |  
  |   | 2023-01-16 10:18:15 | at clojure.lang.PersistentVector.reduce(PersistentVector.java:343) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$cat$fn__8851.invoke(core.clj:7693) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$reduce.invokeStatic(core.clj:6885) |  
  |   | 2023-01-16 10:18:15 | at clojure.core.Eduction.reduce(core.clj:7750) |  
  |   | 2023-01-16 10:18:15 | at clojure.core$transduce.invokeStatic(core.clj:6946) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__61186.reduce(common.clj:34) |  
  |   | 2023-01-16 10:18:15 | at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__61488.invoke(describe_table.clj:89) |  
  |   | 2023-01-16 10:18:15 | at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3068) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.getColumns(ClickHouseDatabaseMetaData.java:829) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:63) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:72) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.client.data.ClickHouseSimpleResponse.of(ClickHouseSimpleResponse.java:123) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.lambda$getColumns$0(ClickHouseDatabaseMetaData.java:832) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.client.ClickHouseColumn.of(ClickHouseColumn.java:407) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.client.ClickHouseColumn.readColumn(ClickHouseColumn.java:206) |  
  |   | 2023-01-16 10:18:15 | at com.clickhouse.client.ClickHouseAggregateFunction.of(ClickHouseAggregateFunction.java:187) |  
  |   | 2023-01-16 10:18:15 | java.lang.IllegalArgumentException: Unknown aggregate function: minIf |  
  |   | 2023-01-16 10:18:15 | 2023-01-16 09:18:15,137 WARN jdbc.ClickHouseDatabaseMetaData :: Failed to read column: AggregateFunction(minIf, Int64, UInt8) |  
  | Log labelsappmetabasecontainermetabasefilename/var/log/pods/metabase_metabase-67cbc98f87-lzbpp_7d9c8ebc-5fb3-4cbd-b3aa-4f6afef3da38/metabase/6.logjob-metabase/metabasenamespace-metabasenode_nameprod-k8s-worker-67cbc98f87-lzbppstreamstdoutDetected fieldsTime1673860695137tsNs1673860695137904040 | Log labels |   |   |   | app | metabase |   |   |   | container | metabase |   |   |   | filename | /var/log/pods/metabase_metabase-67cbc98f87-lzbpp_7d9c8ebc-5fb3-4cbd-b3aa-4f6afef3da38/metabase/6.log |   |   |   | job | metabase/metabase |   |   |   | namespace | metabase |   |   |   | node_name | prod-k8s-worker |   |   |   | pod | metabase-67cbc98f87-lzbpp |   |   |   | stream | stdout | Detected fields |   |   | Time | 1673860695137 |   |   | tsNs | 1673860695137904040
Log labels
  |   |   | app | metabase
  |   |   | container | metabase
  |   |   | filename | /var/log/pods/metabase_metabase-67cbc98f87-lzbpp_7d9c8ebc-5fb3-4cbd-b3aa-4f6afef3da38/metabase/6.log
  |   |   | job | metabase/metabase
  |   |   | namespace | metabase
  |   |   | pod | metabase-67cbc98f87-lzbpp
  |   |   | stream | stdout
Detected fields
  |   | Time | 1673860695137
  |   | tsNs | 1673860695137904040
  |   | 2023-01-16 10:18:11 | 2023-01-16 09:18:11,751 WARN internal.ClickHouseConnectionImpl :: [JDBC Compliant Mode] Transaction is not supported. You may change jdbcCompliant to false to throw SQLException instead. |  
  |   | 2023-01-16 10:18:11 | 2023-01-16 09:18:11,723 WARN internal.ClickHouseConnectionImpl :: [JDBC Compliant Mode] Transaction [8396a8b2-6ee2-48b7-afca-449640f9ecae] (0 queries & 0 savepoints) is committed. |  
  |   | 2023-01-16 10:18:11 | 2023-01-16 09:18:11,723 WARN internal.ClickHouseConnectionImpl :: [JDBC Compliant Mode] Transaction is not supported. You may change jdbcCompliant to false to throw SQLException instead. |  
  |   | 2023-01-16 10:18:11 | 2023-01-16 09:18:11,723 WARN internal.ClickHouseConnectionImpl :: [JDBC Compliant Mode] Transaction [8ed686fb-a004-4be2-b659-7105d31793c2] (1 queries & 0 savepoints) is rolled back. |  
  |   | 2023-01-16 10:18:11 | 2023-01-16 09:18:11,723 WARN internal.ClickHouseConnectionImpl :: [JDBC Compliant Mode] Transaction is not supported. You may change jdbcCompliant to false to throw SQLException instead. |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,404 INFO sync.util :: STARTING: step 'sync-fields' for clickhouse Database 6 'Dev Clickhouse' |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,404 INFO sync.util :: FINISHED: step 'sync-tables' for clickhouse Database 6 'Dev Clickhouse' (2.0 ms) |  
  |   | 2023-01-16 10:18:09 | java.lang.NullPointerException |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,404 WARN sync.util :: Error running step 'sync-tables' for clickhouse Database 6 'Dev Clickhouse' |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,402 INFO sync.util :: STARTING: step 'sync-tables' for clickhouse Database 6 'Dev Clickhouse' |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,402 INFO sync.util :: FINISHED: step 'sync-timezone' for clickhouse Database 6 'Dev Clickhouse' (20.6 ms) |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,381 INFO sync.util :: STARTING: step 'sync-timezone' for clickhouse Database 6 'Dev Clickhouse' |  
  |   | 2023-01-16 10:18:09 | 2023-01-16 09:18:09,380 INFO sync.util :: STARTING: Sync metadata for clickhouse Database 6 'Dev Clickhouse'

```

Any hints on how to resolve this or what might be causing it to fail?

Thanks in advance for looking into this.

**Comment by slvrtrn** [comment]
@phil-schreiber Sorry for the late response. Can you please provide the schema that might cause that `minIf` failure? It will be useful for our investigation.

**Comment by phil-schreiber** [comment]
Thanks for getting back.

A dumbed down schema that would fail looks like this:
`
create table some_table
(
    date        Date,
    some_column AggregateFunction(uniq, String)
)
    engine = Distributed('prod', '_test', 'some_table_base', rand());
`
The AggregateFunction would fail with error:
`AggregateFunction(uniq, String) is not supported`

**Comment by phil-schreiber** [comment]
Maybe moving to https://github.com/ClickHouse/clickhouse-java/releases/tag/v0.4.0 would fix the problem.

**Comment by slvrtrn** [comment]
Thanks @phil-schreiber 
Does it fail with any (Simple)Aggregate function in the table definition?

**Comment by phil-schreiber** [comment]
Hard to tell, can't test them all. But my best guess would be that it's not all of them, it just crashes at the first unsupported one. It's definitely the one mentioned above and minIf

**Comment by slvrtrn** [comment]
@phil-schreiber I tested JDBC v0.4.0 with this sample table:
```sql
create table some_table
(
    date        Date,
    some_column AggregateFunction(uniq, String)
)
    engine = MergeTree order by date;
```

The problem is that these aggregation functions are not supported by the JDBC driver: see how it's processed in the [source code](https://github.com/ClickHouse/clickhouse-java/blob/d175cd7d0e8f0427a8e2bc1b20c597990cd507b4/clickhouse-data/src/main/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessor.java#L510-L515) there - it just throws if it is anything else than `groupBitmap`.

I suspect that we won't be able to support this in the plugin until it is fully implemented in the underlying driver.

**Comment by tom-clickhouse** [comment]
I created an [issue](https://github.com/ClickHouse/clickhouse-java/issues/1232).

**Comment by slvrtrn** [comment]
@phil-schreiber can you please try [1.0.2](https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.0.2) and see if it works for you? It should filter the unsupported column types now. Cheers.
