### ISSUE TITLE
Infinite loop of logs if database no longer exists 

### ISSUE THREAD

**Issue by NicolasBtnr** [ClickHouse/metabase-clickhouse-driver#258]
### Describe the bug
We noticed that if the database inside a clichouse instance is renamed or deleted the Clichouse driver starts logging about 5 million lines every 5 minutes (which has saturated our Datadog quota). Here is the repeating log line:
`at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)`

### Steps to reproduce
1. Rename or a database in clichouse 

### Expected behaviour
Few logs not millions !

### Error log
`at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)`
#### Environment
* metabase-clickhouse-driver version:  1.50.1
* metabase-clickhouse-driver configuration:
* Metabase version: v0.50.6

**Comment by slvrtrn** [comment]
Can you please provide the entire log entry? I will check if it's coming from Metabase itself or the driver.

**Comment by NicolasBtnr** [comment]
Hi,
here is a rough extract of logs:
`"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$2.activeCheckConnectionNoQuery(DefaultConnectionTester.java:136)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.isValid(ClickHouseConnectionImpl.java:911)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:959)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)"
"2024-07-11T09:15:59.978Z",,"""metabase""","at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)"
"2024-07-11T09:15:59.978Z",,"""metabase""","java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 81. DB::Exception: Database staging does not exist. (UNKNOWN_DATABASE) (version 24.2.2.16370 (official build))"
"2024-07-11T09:15:59.978Z",,"""metabase""","... 1006 more"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$2.activeCheckConnectionNoQuery(DefaultConnectionTester.java:136)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.isValid(ClickHouseConnectionImpl.java:911)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:959)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)"
"2024-07-11T09:15:59.977Z",,"""metabase""","java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 81. DB::Exception: Database staging does not exist. (UNKNOWN_DATABASE) (version 24.2.2.16370 (official build))"
"2024-07-11T09:15:59.977Z",,"""metabase""","... 1006 more"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$2.activeCheckConnectionNoQuery(DefaultConnectionTester.java:136)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.isValid(ClickHouseConnectionImpl.java:911)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:958)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:2144)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:200)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:246)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:203)"
"2024-07-11T09:15:59.977Z",,"""metabase""","Caused by: java.io.IOException: Code: 81. DB::Exception: Database staging does not exist. (UNKNOWN_DATABASE) (version 24.2.2.16370 (official build))"
"2024-07-11T09:15:59.977Z",,"""metabase""","... 1008 more"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$2.activeCheckConnectionNoQuery(DefaultConnectionTester.java:136)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.isValid(ClickHouseConnectionImpl.java:911)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:958)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:2144)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:200)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:246)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:203)"
"2024-07-11T09:15:59.977Z",,"""metabase""","Caused by: java.io.IOException: Code: 81. DB::Exception: Database staging does not exist. (UNKNOWN_DATABASE) (version 24.2.2.16370 (official build))"
"2024-07-11T09:15:59.977Z",,"""metabase""","... 1008 more"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.977Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:504)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:79)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:275)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$3.activeCheckConnectionNoQuery(DefaultConnectionTester.java:180)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.c3p0.impl.DefaultConnectionTester$2.activeCheckConnectionNoQuery(DefaultConnectionTester.java:136)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.isValid(ClickHouseConnectionImpl.java:911)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.ClickHouseClientBuilder$Agent.ping(ClickHouseClientBuilder.java:317)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.AbstractClient.ping(AbstractClient.java:338)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.ClickHouseClient.ping(ClickHouseClient.java:958)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:2144)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:282)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:151)"
"2024-07-11T09:15:59.976Z",,"""metabase""","Caused by: com.clickhouse.client.ClickHouseException: Code: 81. DB::Exception: Database staging does not exist. (UNKNOWN_DATABASE) (version 24.2.2.16370 (official build))"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"
"2024-07-11T09:15:59.976Z",,"""metabase""","at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)"`

**Comment by calherries** [comment]
Thanks, I repro'd on 0.50.6 and 0.50.8. Steps:
1. Set up a database in ClickHouse. e.g.
```
clickhouse-client -q "CREATE DATABASE IF NOT EXISTS db;"
clickhouse-client -q "CREATE TABLE db.table_1 (c_1 Int32) ENGINE = MergeTree() ORDER BY c_1;"
```
2. Add the database in Metabase Admin Settings.
3. Rename the database in ClickHouse. e.g.
```
clickhouse-client -q "RENAME DATABASE db TO newdb;"
```
4. Query from the table created in step 1. Go to Home > Databases > the clickhouse DB > the table. 
5.
